const data={
    products: [
    {
        name : 'Iphone 13',
        slug : '101',
        category : 'phone',
        image : '/images/iphone13.jpg',
        price : 85000,
        countInStock : 10,
        brand : 'apple',
        rating : 8.5,
        description : 'Better phone for productive works',
    },
    {
        name : 'Realme 6',
        slug : '102',
        category : 'phone',
        image : '/images/realme6.jpg',
        price : 15000,
        countInStock : 20,
        brand : 'Real me',
        rating : 8.3,
        description : 'Better phone for productive works',
    },
    {
        name : 'Samsung Galaxy A 53',
        category : 'phone',
        slug : '103',
        image : '/images/sga53.jpg',
        price : 35000,
        countInStock : 10,
        brand : 'Samsung',
        rating : 8.5,
        description : 'Better phone for productive works',
    },
    {
        name : 'Redmi Note 11T',
        slug : '104',
        category : 'phone',
        image : '/images/redminote11t5g.jpg',
        price : 55000,
        countInStock : 10,
        brand : 'Redmi Node',
        rating : 8.5,
        description : 'Better phone for productive works',
    },
    {
        name : 'Redmi Note 11T',
        slug : '104',
        category : 'phone',
        image : '/images/mrg71.png',
        price : 55000,
        countInStock : 10,
        brand : 'Redmi Node',
        rating : 8.5,
        description : 'Better phone for productive works',
    },
],
};

export default data;